# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://artivis.github.io"
baseurl: ""

avatar_url: "http://artivis.github.io"
navbar_brand_url: "http://artivis.github.io/hw.html"

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: My (first) website

# Short description of your site
description: You can't stop progress... I guess

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Projects:
    # - project list: "projects"
    - catkin-build-tools: "catkin-build-tools"
  About/Contact: "aboutme"
  # Resources:
  #   - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
  #   - Learn markdown: "http://www.markdowntutorial.com/"
  #   - GitHub Pages: "https://pages.github.com/"
  # Author's home: "http://deanattali.com"
  CV: "https://www.linkedin.com/in/jeremiederay"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"

# Todo figure out auto google cse
# Enable/disable search on artivis.github.io
nav-search: true

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Jeremie Deray
  email: "seethat@later.com"
  github: artivis
  linkedin: jeremiederay
  stackoverflow: yourlink
  youtube: user/MoreHighSound

# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: false
  email: true
  twitter: false
  google-plus: false
  github: true
  linkedin: true
  xing: false
  stackoverflow: true
  snapchat: false
  instagram: false
  youtube: true
  spotify: false

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "MyWebsite.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Spain"
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 10

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags pages (not recommended if you are deploying via GitHub pages, only set to true if deploying locally with ruby)
link-tags: false

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."
    _posts/_projects:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

gems:
  - jekyll-paginate

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
